[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "a"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
module-name = "a"
bindings = "uniffi"
manifest-path = "crates/a/Cargo.toml"
